[build]
  command = "npm run build"   # The build command (it runs npm build inside frontend)
  publish = "frontend/dist"   # The folder where the build output is generated

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
